# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This is a Kconfig fragment which can be used to enable debug-related options
# in the application. See the README for more details.

CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_DBG=y
# CONFIG_CAN_LOG_LEVEL_DBG=y
CONFIG_CAN_LOOPBACK=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKENDS=y
CONFIG_SERIAL=y
CONFIG_UART_NATIVE_PTY_0_ON_STDINOUT=y
CONFIG_SHELL_PRINTF_BUFF_SIZE=100
CONFIG_CAN_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_GPIO_EMUL=y
CONFIG_SHELL_TELNET_LOG_LEVEL_DBG=y
